export enum UserTier {
  FREE = "FREE",
  PREMIUM = "PREMIUM",
}

export enum RateLimitAlgorithmType {
  FIXED_WINDOW_COUNTER = "FIXED_WINDOW_COUNTER",
  SLIDING_WINDOW_LOG = "SLIDING_WINDOW_LOG",
  SLIDING_WINDOW_COUNTER = "SLIDING_WINDOW_COUNTER",
  TOKEN_BUCKET = "TOKEN_BUCKET",
  LEAKY_BUCKET = "LEAKY_BUCKET",
}
